## YAML Template
---
default: --format pretty #-p html 
# ci: --format progress -p html #-p #qa -p headless
html: --format html --out=results/report.html
json: --format json --out=results/report.json
chrome: BROWSER=chrome
firefox: BROWSER=firefox
ie: BROWSER=ie
# headless: BROWSER=headless